language: python
python:
- '3.6'
- '3.7'
- '3.8'
- 3.9-dev
install:
- pip install .
script:
- pytest
deploy:
  provider: pypi
  user: __token__
  password:
    secure: EVT3fsgGug80w+qorrCMrE5BYkZfwy0eWvg6imqMuHGttQs98ddrNotKqKJJIxp8KpwqprxaYbgpWdaOY12TAub6NLZrWdXnhJgrE7ZmXwl8AL+wGI6wde8moYSMUeODhXbM9HcwjSEwyenTSBbIymiEEmViljLyw7DPQleMgcbq4YP/WYBofiZ7qM3FibYoiLTuuFQ7/Nz3KuCZ+jw58/KAPVA9lsA5Ljat63tE2HlLhbgNPfAe6CbLZP2wItr3TE0V6Q/VuFlhCc/TLDF7EVgfpXYlseKml8iTBa97UQq+TSAjTTxY7FK+SuVXO2dcDmPweB8Yc1+zSpbULTy95GB8+3HaiY3L+PjmAICj+CSwV0HaZErmB3poTdR42lDcC+1TZd1BZi6/7RKBx/JIfNwnqaGQh3Ou+WRR8F8/HIND4RfzmTinXercmxW8jI0bDtuElIEtnghHSj2U0wX70wqHSEEeC3OGqgCXOckfHdJnN/yiCMlwFjV4zBWyA3Ufq9TuLFMHNz6r6RBq7GNzvJSESqy4RyoqgV/Mu064Yhpg0pDs78bwDR+4UJtZqJDBwEfAh7fhIHLiv9zJPIEfUWmrZXwq63dse9M0BIkWvqFKHHIVVxJspIkecHynDBo5b3Rt9+ZBCRV6sEys3y/9+KGboDj+zUEOap/H9hzCBqw=
  on:
    tags: true
    python: 3.6
